#!/usr/bin/env python3
"""Build `jarvis` as a real model in Ollama, rather than a prompt bolted on top.

A system prompt is something you hand a stranger each time you meet them. This
bakes the identity into a named model in Ollama's own registry, so `ollama list`
shows `jarvis`, `ollama run jarvis` talks to it directly, and nothing that reads
the model can mistake it for the base it was built from.

    python deploy/build_model.py                 # auto-size the base
    python deploy/build_model.py --base qwen3:4b # pin the base
    python deploy/build_model.py --name butler   # call it something else

The weights are not copied. Ollama layers this on the base model, so a build
costs a few kilobytes and takes about a second.
"""

import argparse
import json
import subprocess
import sys
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from core import config, hardware, persona  # noqa: E402

# Ollama parses Modelfiles itself, so the persona is written once in persona.py
# and injected here. Keep the triple quotes: the text contains apostrophes.
TEMPLATE = '''# Generated by deploy/build_model.py - edits here are overwritten.
# Rebuild with: python deploy/build_model.py

FROM {base}

PARAMETER temperature {temperature}
PARAMETER num_ctx {num_ctx}

SYSTEM """{system}"""
'''


def ollama_up(host: str) -> bool:
    try:
        with urllib.request.urlopen(f"{host}/api/tags", timeout=5) as resp:
            return resp.status == 200
    except Exception:  # noqa: BLE001
        return False


def installed(host: str) -> list[str]:
    try:
        with urllib.request.urlopen(f"{host}/api/tags", timeout=5) as resp:
            return [m["name"] for m in json.loads(resp.read()).get("models", [])]
    except Exception:  # noqa: BLE001
        return []


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the jarvis model in Ollama.")
    parser.add_argument("--base", help="Base model tag. Default: sized to this machine.")
    parser.add_argument("--name", default="jarvis", help="Name to build as.")
    parser.add_argument("--keep", action="store_true", help="Keep the Modelfile on disk.")
    args = parser.parse_args()

    host = config.OLLAMA_HOST.rstrip("/")
    if not ollama_up(host):
        print(f"No Ollama server at {host}. Start it first.")
        return 1

    base = args.base or hardware.suggest_model()[0]
    have = installed(host)
    if base not in have and f"{base}:latest" not in have:
        print(f"Base model '{base}' is not downloaded yet.")
        print(f"Run:  ollama pull {base}")
        return 1

    # The identity text only; the memory and clock sections are per-turn and are
    # still assembled at runtime by persona.build_system_prompt.
    system = persona.CHARACTER.format(user="the user").strip()

    modelfile = TEMPLATE.format(
        base=base,
        temperature=config.TEMPERATURE,
        num_ctx=config.CONTEXT_TOKENS,
        system=system,
    )

    path = Path(__file__).resolve().parent / "Modelfile"
    path.write_text(modelfile, encoding="utf-8")

    print(f"Building '{args.name}' from '{base}'...")
    result = subprocess.run(
        ["ollama", "create", args.name, "-f", str(path)],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        print("Build failed:")
        print(result.stdout.strip() or result.stderr.strip())
        return 1

    if not args.keep:
        path.unlink(missing_ok=True)

    print(f"\nBuilt '{args.name}'. It is now a model in its own right:")
    print(f"  ollama list            shows {args.name}")
    print(f"  ollama run {args.name}      talks to it without Jarvis at all")
    print(f"  python jarvis.py       picks it up automatically")
    return 0


if __name__ == "__main__":
    sys.exit(main())
